# currently a quarto project is required for metadata or brand extensions to work
project:
  type: website

website:
  navbar:
    left:
      - href: example-osc-base.qmd
        text: Brand
      - href: example-osc-tutorial.qmd
        text: Tutorial
